import Image from 'next/image'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div>
      <head>
        <title>Platzi</title>
        <meta name="description" content="Generated by Jorge" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <main>
        <h1>Hello Moto</h1>
      </main> 
      <footer>
      </footer>     
    </div>

  )
}
